[theme]
base                     = "light"
primaryColor             = "#1a2035"
backgroundColor          = "#f0f2f5"
secondaryBackgroundColor = "#ffffff"
textColor                = "#111827"

[server]
headless   = true
enableCORS = false
